development:
    adapter: postgresql
    encoding: utf8
    database: elmpmnhh
    username: elmpmnhh
    pool: 5
    password: cnV0F-iyy-PrXBih2l_nbg_9MKXVI00z
    host:  	babar.db.elephantsql.com
test:
  adapter: postgresql
  encoding: utf8
  database: sxxrdthy
  username: sxxrdthy
  pool: 5
  password: e327938wshO27Z-i6zQbDz9t8gNVCdpV
  host:  	babar.db.elephantsql.com

