development:
  adapter: postgresql
  encoding: unicode
  username: david
  database: development_project
  password: 12345678
  host: database-1.c5ik7vhqusax.sa-east-1.rds.amazonaws.com
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  username: david
  database: test_project
  password: 12345678
  host: database-1.c5ik7vhqusax.sa-east-1.rds.amazonaws.com
  port: 5432

